services:
  ghost:
    image: ghost:5
    container_name: ghost
    ports:
      - "2368:2368"
    volumes:
      - ghost_data:/var/lib/ghost/content
    environment:
      url: https://2db7-2409-40e3-399-faa0-90eb-d198-6eef-e99a.ngrok-free.app
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghostpass
      database__connection__database: ghost
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8
    container_name: ghost-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: k%23rtikyadav123
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - ghost_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ghost_data:
  ghost_mysql:
