apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: "http://localhost:2368"
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "mysql"
            - name: database__connection__user
              value: "ghost"
            - name: database__connection__password
              value: "ghostpass"
            - name: database__connection__database
              value: "ghost"
          volumeMounts:
            - name: ghost-volume
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-volume
          persistentVolumeClaim:
            claimName: ghost-pvc
